name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - '_posts/**'
  schedule:
    - cron: '30 8 * * 1,3,5' # Runs at 08:30 AM Madrid time (UTC+1 or UTC+2 depending on daylight saving)
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate article script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          INDEXNOW_API_KEY: ${{ secrets.INDEXNOW_API_KEY }}
        run: python AI_scripts/generate_article.py

      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}