name: Scheduled Article Generation

on:
  schedule:
    - cron: '30 8 * * 1,3,5' # Runs at 08:30 AM Madrid time (UTC+1 or UTC+2 depending on daylight saving)
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  generate_article:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Ensure you have a requirements.txt file with necessary packages

      - name: Run article generation script
        run: python AI_scripts/generate_article.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}