name: Schedule and Publish AI Articles

on:
  schedule:
    - cron: '30 8 * * 1,3,5' # Runs at 08:30 AM Madrid time (UTC+1 or UTC+2 depending on daylight saving)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate_article:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run generate article script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python AI_scripts/generate_article.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Add generated article and image"
        git push